"""建立通知、收件箱与运维基础模型

Revision ID: 20260820_0001
Revises:
Create Date: 2026-08-20 11:10:01.380046
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260820_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("aggregate_type", sa.String(length=32), nullable=False),
        sa.Column("aggregate_id", sa.String(length=255), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_audit_time", "notification_audit_events", ["occurred_at"], unique=False
    )
    op.create_table(
        "notification_channel_principals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recipient_issuer", sa.String(length=512), nullable=False),
        sa.Column("recipient_subject", sa.String(length=255), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("sender_id", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel", "account_id", "sender_id", name="uq_channel_principal"),
    )
    op.create_index(
        op.f("ix_notification_channel_principals_channel"),
        "notification_channel_principals",
        ["channel"],
        unique=False,
    )
    op.create_table(
        "notification_channel_targets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recipient_issuer", sa.String(length=512), nullable=False),
        sa.Column("recipient_subject", sa.String(length=255), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("target_kind", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.String(length=255), nullable=False),
        sa.Column("thread_id", sa.String(length=255), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("is_home", sa.Boolean(), nullable=False),
        sa.Column("min_severity", sa.String(length=16), nullable=False),
        sa.Column("categories", sa.JSON(), nullable=False),
        sa.Column("require_mention", sa.Boolean(), nullable=False),
        sa.Column("command_level", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "channel",
            "account_id",
            "target_kind",
            "target_id",
            "thread_id",
            name="uq_channel_target",
        ),
    )
    op.create_index(
        "ix_channel_target_recipient",
        "notification_channel_targets",
        ["recipient_issuer", "recipient_subject", "enabled"],
        unique=False,
    )
    op.create_table(
        "notification_chat_ingress_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("gateway_app_id", sa.String(length=64), nullable=False),
        sa.Column("source_event_id", sa.String(length=255), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("peer_kind", sa.String(length=16), nullable=False),
        sa.Column("peer_id", sa.String(length=255), nullable=False),
        sa.Column("thread_id", sa.String(length=255), nullable=False),
        sa.Column("sender_id", sa.String(length=255), nullable=False),
        sa.Column("command", sa.String(length=32), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gateway_app_id", "source_event_id", name="uq_chat_ingress_event"),
    )
    op.create_index(
        "ix_chat_ingress_time", "notification_chat_ingress_events", ["created_at"], unique=False
    )
    op.create_table(
        "notification_local_identities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("issuer", sa.String(length=512), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issuer", "subject", name="uq_notification_identity"),
    )
    op.create_table(
        "notification_oidc_transactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("state_hash", sa.LargeBinary(), nullable=False),
        sa.Column("browser_binding_hash", sa.LargeBinary(), nullable=False),
        sa.Column("nonce_hash", sa.LargeBinary(), nullable=False),
        sa.Column("pkce_verifier_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("redirect_uri", sa.String(length=1024), nullable=False),
        sa.Column("return_to", sa.String(length=1024), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_hash"),
    )
    op.create_index(
        op.f("ix_notification_oidc_transactions_expires_at"),
        "notification_oidc_transactions",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "notification_operation_probes",
        sa.Column("service_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("service_id"),
    )
    op.create_index(
        op.f("ix_notification_operation_probes_status"),
        "notification_operation_probes",
        ["status"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_app_id", sa.String(length=64), nullable=False),
        sa.Column("source_event_id", sa.String(length=128), nullable=False),
        sa.Column("recipient_issuer", sa.String(length=512), nullable=False),
        sa.Column("recipient_subject", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("resource_uri", sa.String(length=1024), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("delivery_mode", sa.String(length=16), nullable=False),
        sa.Column("requested_channels", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_app_id",
            "source_event_id",
            "recipient_issuer",
            "recipient_subject",
            name="uq_notification_source_recipient",
        ),
    )
    op.create_index(op.f("ix_notifications_category"), "notifications", ["category"], unique=False)
    op.create_index(
        "ix_notifications_recipient_state_time",
        "notifications",
        ["recipient_issuer", "recipient_subject", "state", "occurred_at"],
        unique=False,
    )
    op.create_index(op.f("ix_notifications_severity"), "notifications", ["severity"], unique=False)
    op.create_index(
        "ix_notifications_source_time",
        "notifications",
        ["source_app_id", "occurred_at"],
        unique=False,
    )
    op.create_index(op.f("ix_notifications_state"), "notifications", ["state"], unique=False)
    op.create_table(
        "notification_browser_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("identity_id", sa.String(length=36), nullable=False),
        sa.Column("session_hash", sa.LargeBinary(), nullable=False),
        sa.Column("groups_snapshot", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["identity_id"], ["notification_local_identities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_hash"),
    )
    op.create_index(
        op.f("ix_notification_browser_sessions_expires_at"),
        "notification_browser_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_browser_sessions_identity_id"),
        "notification_browser_sessions",
        ["identity_id"],
        unique=False,
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("notification_id", sa.String(length=36), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("target_kind", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.String(length=255), nullable=False),
        sa.Column("thread_id", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("last_error_code", sa.String(length=128), nullable=True),
        sa.Column("last_error_detail", sa.String(length=500), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["notification_id"], ["notifications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "notification_id",
            "channel",
            "account_id",
            "target_kind",
            "target_id",
            "thread_id",
            name="uq_notification_delivery_target",
        ),
    )
    op.create_index(
        op.f("ix_notification_deliveries_channel"),
        "notification_deliveries",
        ["channel"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_notification_id"),
        "notification_deliveries",
        ["notification_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_state"), "notification_deliveries", ["state"], unique=False
    )
    op.create_index(
        "ix_notification_delivery_ready",
        "notification_deliveries",
        ["state", "available_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notification_delivery_ready", table_name="notification_deliveries")
    op.drop_index(op.f("ix_notification_deliveries_state"), table_name="notification_deliveries")
    op.drop_index(
        op.f("ix_notification_deliveries_notification_id"), table_name="notification_deliveries"
    )
    op.drop_index(op.f("ix_notification_deliveries_channel"), table_name="notification_deliveries")
    op.drop_table("notification_deliveries")
    op.drop_index(
        op.f("ix_notification_browser_sessions_identity_id"),
        table_name="notification_browser_sessions",
    )
    op.drop_index(
        op.f("ix_notification_browser_sessions_expires_at"),
        table_name="notification_browser_sessions",
    )
    op.drop_table("notification_browser_sessions")
    op.drop_index(op.f("ix_notifications_state"), table_name="notifications")
    op.drop_index("ix_notifications_source_time", table_name="notifications")
    op.drop_index(op.f("ix_notifications_severity"), table_name="notifications")
    op.drop_index("ix_notifications_recipient_state_time", table_name="notifications")
    op.drop_index(op.f("ix_notifications_category"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        op.f("ix_notification_operation_probes_status"), table_name="notification_operation_probes"
    )
    op.drop_table("notification_operation_probes")
    op.drop_index(
        op.f("ix_notification_oidc_transactions_expires_at"),
        table_name="notification_oidc_transactions",
    )
    op.drop_table("notification_oidc_transactions")
    op.drop_table("notification_local_identities")
    op.drop_index("ix_chat_ingress_time", table_name="notification_chat_ingress_events")
    op.drop_table("notification_chat_ingress_events")
    op.drop_index("ix_channel_target_recipient", table_name="notification_channel_targets")
    op.drop_table("notification_channel_targets")
    op.drop_index(
        op.f("ix_notification_channel_principals_channel"),
        table_name="notification_channel_principals",
    )
    op.drop_table("notification_channel_principals")
    op.drop_index("ix_notification_audit_time", table_name="notification_audit_events")
    op.drop_table("notification_audit_events")
    # ### end Alembic commands ###
